[tool.poetry]
name = "my_project"
version = "0.1.0"
description = "CLI приложение для проверки HTTP методов"
authors = ["<email@example.com>"]

[tool.poetry.dependencies]
python = "^3.9"
aiohttp = "^3.8.0"

[tool.poetry.dev-dependencies]
pytest = "^7.0"
pytest-asyncio = "^0.18.3"
coverage = "^6.3"

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"
